### ISSUE TITLE
`alloc-dealloc-mismatch ` when converting svg to png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1030]
Sadly I don't have minimal file to reproduce
```
=================================================================
==93873==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete) on 0x60700001ad50
    #0 0x7fbcf3f0322f in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x7fbcf3bf4a52 in SvgLoader::close() ../src/loaders/svg/tvgSvgLoader.cpp:2984
    #2 0x7fbcf3b61d02 in tvg::Picture::Impl::reload() (/home/rafal/test/thorvg/build/src/bin/svg2png/../../libthorvg.so.0+0x1f1d02)
    #3 0x7fbcf3b62cc5 in tvg::PaintMethod<tvg::Picture::Impl>::update(tvg::RenderMethod&, tvg::RenderTransform const*, unsigned int, tvg::Array<void*>&, tvg::RenderUpdateFlag) (/home/rafal/test/thorvg/build/src/bin/svg2png/../../libthorvg.so.0+0x1f2cc5)
    #4 0x7fbcf3b58536 in tvg::Paint::Impl::update(tvg::RenderMethod&, tvg::RenderTransform const*, unsigned int, tvg::Array<void*>&, unsigned int) ../src/lib/tvgPaint.cpp:231
    #5 0x7fbcf3b49169 in tvg::Canvas::Impl::update(tvg::Paint*, bool) ../src/lib/tvgCanvasImpl.h:96
    #6 0x7fbcf3b47a73 in tvg::Canvas::Impl::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) ../src/lib/tvgCanvasImpl.h:57
    #7 0x7fbcf3b47a73 in tvg::Canvas::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) ../src/lib/tvgCanvas.cpp:48
    #8 0x55bced298aec in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ../src/bin/svg2png/svg2png.cpp:112
    #9 0x55bced299aa5 in App::renderFile(char const*) ../src/bin/svg2png/svg2png.cpp:292
    #10 0x55bced29a069 in App::handleDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, __dirstream*) ../src/bin/svg2png/svg2png.cpp:331
    #11 0x55bced29b09e in App::setup(int, char**) ../src/bin/svg2png/svg2png.cpp:229
    #12 0x55bced293f79 in main ../src/bin/svg2png/svg2png.cpp:343
    #13 0x7fbcf2bd0fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x7fbcf2bd107c in __libc_start_main_impl ../csu/libc-start.c:409
    #15 0x55bced294074 in _start (/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png+0x9a074)

0x60700001ad50 is located 0 bytes inside of 80-byte region [0x60700001ad50,0x60700001ada0)
allocated by thread T5 here:
    #0 0x7fbcf3f00a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fbcf3bf1d1d in _createLinearGradient ../src/loaders/svg/tvgSvgLoader.cpp:2288
    #2 0x7fbcf3c01804 in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2429
    #3 0x7fbcf3c01f72 in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2467
    #4 0x7fbcf3c1a3f8 in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:417
    #5 0x7fbcf3c034a8 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2833
    #6 0x7fbcf3b80a89 in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #7 0x7fbcf3b80a89 in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #8 0x7fbcf3831693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)

Thread T5 created by T0 here:
    #0 0x7fbcf3ea4685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7fbcf3831969 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda969)
    #2 0x7fbcf3b88005 in void __gnu_cxx::new_allocator<std::thread>::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/ext/new_allocator.h:162
    #3 0x7fbcf3b88005 in void std::allocator_traits<std::allocator<std::thread> >::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::allocator<std::thread>&, std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/alloc_traits.h:512
    #4 0x7fbcf3b88005 in void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_insert<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:449
    #5 0x7fbcf3b7f1f1 in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:121
    #6 0x7fbcf3b7f1f1 in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:109
    #7 0x7fbcf3b7f1f1 in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int) ../src/lib/tvgTaskScheduler.cpp:113
    #8 0x7fbcf3b7f1f1 in tvg::TaskScheduler::init(unsigned int) ../src/lib/tvgTaskScheduler.cpp:170
    #9 0x7fbcf3b4c1c7 in tvg::Initializer::init(tvg::CanvasEngine, unsigned int) ../src/lib/tvgInitializer.cpp:111
    #10 0x55bced296b63 in Renderer::createCanvas() ../src/bin/svg2png/svg2png.cpp:144
    #11 0x55bced297978 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ../src/bin/svg2png/svg2png.cpp:64
    #12 0x55bced299aa5 in App::renderFile(char const*) ../src/bin/svg2png/svg2png.cpp:292
    #13 0x55bced29a069 in App::handleDirectory(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, __dirstream*) ../src/bin/svg2png/svg2png.cpp:331
    #14 0x55bced29b09e in App::setup(int, char**) ../src/bin/svg2png/svg2png.cpp:229
    #15 0x55bced293f79 in main ../src/bin/svg2png/svg2png.cpp:343
    #16 0x7fbcf2bd0fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172 in operator delete(void*, unsigned long)
==93873==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==93873==ABORTING

```

**Comment by qarmin** [comment]
Example file -
[AudioStreamMP3.svg.zip](https://github.com/Samsung/thorvg/files/7519458/AudioStreamMP3.svg.zip)

**Comment by hermet** [comment]
@qarmin @mgrudzinska  thanks!
