### ISSUE TITLE
Crash when rasterizing svg image

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#1118]
SVG file : [Godot.Planner.2021-11-06.zip](https://github.com/Samsung/thorvg/files/7731527/Godot.Planner.2021-11-06.zip)

After patch 06cef2a710f2bb27900eb509c4ae38a034c742ea, crash occurs when rasterizing image.
 

[BT]

```
SVG: //home/junsu/dev/os/thorvg/src/examples/images/Godot.Planner.2021-11-06.svg

Thread 1 "Svg" received signal SIGBUS, Bus error.
_interpDownScaler (img=<optimized out>, w=<optimized out>, rX=rX@entry=4294967247, rY=rY@entry=38, n=29, h=<optimized out>) at ../src/lib/sw_engine/tvgSwRaster.cpp:115
warning: Source file is more recent than executable.
115	            c[2] += (*p >> 8) & 0xff;
(gdb) bt
#0  _interpDownScaler (img=<optimized out>, w=<optimized out>, rX=rX@entry=4294967247, rY=rY@entry=38, n=29, h=<optimized out>) at ../src/lib/sw_engine/tvgSwRaster.cpp:115
#1  0x00007ffff7bc00e3 in _rasterScaledRGBAImage (halfScale=29, region=..., itransform=0x7fffffffcaac, image=0x555555da65a8, surface=0x555555dad4e0)
    at ../src/lib/sw_engine/tvgSwRaster.cpp:779
#2  _scaledRGBAImage (opacity=<optimized out>, region=..., transform=<optimized out>, image=0x555555da65a8, surface=0x555555dad4e0) at ../src/lib/sw_engine/tvgSwRaster.cpp:821
#3  _rasterRGBAImage (opacity=<optimized out>, region=..., transform=<optimized out>, image=0x555555da65a8, surface=0x555555dad4e0) at ../src/lib/sw_engine/tvgSwRaster.cpp:959
#4  rasterImage (surface=0x555555dad4e0, image=0x555555da65a8, transform=<optimized out>, bbox=..., opacity=<optimized out>) at ../src/lib/sw_engine/tvgSwRaster.cpp:1479
#5  0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x7fffd413cf70, renderer=...) at ../src/lib/tvgPaint.cpp:178
#6  0x00007ffff7bb6bd2 in tvg::Scene::Impl::render (this=0x7fffd413cf00, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#7  0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x7fffd413ced0, renderer=...) at ../src/lib/tvgPaint.cpp:178
#8  0x00007ffff7bb6bd2 in tvg::Scene::Impl::render (this=0x7fffd40fd110, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#9  0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x7fffd40fd0e0, renderer=...) at ../src/lib/tvgPaint.cpp:178
#10 0x00007ffff7bb6bd2 in tvg::Scene::Impl::render (this=0x7fffd41561a0, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#11 0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x7fffd4156170, renderer=...) at ../src/lib/tvgPaint.cpp:178
#12 0x00007ffff7bb6bd2 in tvg::Scene::Impl::render (this=0x7fffd4156280, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#13 0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x7fffd4156250, renderer=...) at ../src/lib/tvgPaint.cpp:178
#14 0x00007ffff7bb4ba3 in tvg::Paint::Impl::render (this=0x555555dae380, renderer=...) at ../src/lib/tvgPaint.cpp:178
#15 0x00007ffff7bb346e in tvg::Canvas::Impl::draw (this=0x555555dad570) at ../src/lib/tvgCanvasImpl.h:119
#16 tvg::Canvas::Impl::draw (this=0x555555dad570) at ../src/lib/tvgCanvasImpl.h:113
#17 tvg::Canvas::draw (this=<optimized out>) at ../src/lib/tvgCanvas.cpp:60
#18 0x00005555555562d6 in drawSwView (data=<optimized out>, obj=<optimized out>) at ../src/examples/Svg.cpp:107
#19 0x00007ffff716922c in evas_process_dirty_pixels (pixels=<optimized out>, surface=<optimized out>, output=<optimized out>, engine=<optimized out>, o=<optimized out>, 
    obj=0x555555dae550, eo_obj=<optimized out>) at ../src/lib/evas/canvas/evas_object_image.c:1894
#20 _evas_image_pixels_get (eo_obj=eo_obj@entry=0x400000026408, obj=obj@entry=0x555555dae550, engine=engine@entry=0x555555cef030, output=output@entry=0x555555cf19d0, 
    context=context@entry=0x555555db4f00, surface=surface@entry=0x555555a78240, x=<optimized out>, y=<optimized out>, imagew=<optimized out>, imageh=<optimized out>, 
    uvw=<optimized out>, uvh=<optimized out>, filtered=<optimized out>, needs_post_render=0 '\000') at ../src/lib/evas/canvas/evas_object_image.c:2318
#21 0x00007ffff71697e0 in _evas_image_render (eo_obj=eo_obj@entry=0x400000026408, obj=obj@entry=0x555555dae550, engine=engine@entry=0x555555cef030, 
    output=output@entry=0x555555cf19d0, context=context@entry=0x555555db4f00, surface=surface@entry=0x555555a78240, x=0, y=0, l=0, t=0, r=0, b=0, skip_map=0 '\000', 
    do_async=1 '\001') at ../src/lib/evas/canvas/evas_object_image.c:2468
#22 0x00007ffff716a98e in evas_object_image_render (eo_obj=0x400000026408, obj=0x555555dae550, type_private_data=0x555555dae670, engine=0x555555cef030, output=0x555555cf19d0, 
    context=0x555555db4f00, surface=0x555555a78240, x=0, y=0, do_async=1 '\001') at ../src/lib/evas/canvas/evas_object_image.c:2271
#23 0x00007ffff71d111d in evas_render_mapped (evas=evas@entry=0x555555ce2cc0, eo_obj=eo_obj@entry=0x400000026408, obj=obj@entry=0x555555dae550, 
    context=context@entry=0x555555d57170, output=output@entry=0x555555cf19d0, surface=surface@entry=0x555555a78240, off_x=<optimized out>, off_y=<optimized out>, 
    mapped=<optimized out>, ecx=<optimized out>, ecy=<optimized out>, ecw=<optimized out>, ech=<optimized out>, proxy_render_data=<optimized out>, level=<optimized out>, 
    do_async=<optimized out>) at ../src/lib/evas/canvas/evas_render.c:2290
#24 0x00007ffff71d2e57 in evas_render_updates_internal_loop (eo_e=eo_e@entry=0x400000007b8c, evas=evas@entry=0x555555ce2cc0, output=0x555555cf19d0, 
    surface=surface@entry=0x555555a78240, context=context@entry=0x555555d57170, top=top@entry=0x0, ux=0, uy=0, uw=800, uh=800, cx=0, cy=0, cw=800, ch=800, fx=0, fy=0, 
    skip_cutouts=0 '\000', cutout_margin=0x0, alpha=0 '\000', do_async=1 '\001', offset=0x7fffffffd36c, level=0) at ../src/lib/evas/canvas/evas_render.c:3158
#25 0x00007ffff71d5854 in evas_render_updates_internal (eo_e=eo_e@entry=0x400000007b8c, make_updates=make_updates@entry=1 '\001', do_draw=do_draw@entry=1 '\001', 
    do_async=do_async@entry=1 '\001') at ../src/lib/evas/canvas/evas_render.c:3631
#26 0x00007ffff71d725e in _evas_canvas_render_async (eo_e=0x400000007b8c, e=<optimized out>) at ../src/lib/evas/canvas/evas_render.c:4094
#27 0x00007ffff71522cc in evas_canvas_render_async (obj=<optimized out>) at ../src/lib/evas/canvas/evas_canvas_eo.c:168
#28 0x00007ffff715bc67 in evas_render_async (obj=<optimized out>) at ../src/lib/evas/canvas/evas_canvas_eo.legacy.c:179
#29 0x00007fffe22b8536 in _ecore_evas_x_render (ee=0x555555cdcf20) at ../src/modules/ecore_evas/engines/x/ecore_evas_x.c:761
#30 0x00007ffff4bdede3 in _ecore_evas_idle_enter (data=<optimized out>) at ../src/lib/ecore_evas/ecore_evas.c:295
#31 0x00007ffff4e0f975 in _ecore_call_task_cb (data=<optimized out>, func=<optimized out>) at ../src/lib/ecore/ecore_private.h:456
#32 _ecore_factorized_idle_process (data=0x555555a1d290, event=<optimized out>) at ../src/lib/ecore/ecore_idler.c:35
#33 0x00007ffff5090082 in _event_callback_call (legacy_compare=0 '\000', event_info=<optimized out>, desc=0x7ffff50742d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, pd=0x555555a10760, 
    obj_id=0x40000000036e) at ../src/lib/eo/eo_base_class.c:2114
#34 _efl_object_event_callback_call (obj_id=0x40000000036e, pd=0x555555a10760, desc=0x7ffff50742d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, event_info=<optimized out>)
    at ../src/lib/eo/eo_base_class.c:2186
#35 0x00007ffff5089d23 in efl_event_callback_call (obj=obj@entry=0x40000000036e, desc=0x7ffff50742d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, event_info=event_info@entry=0x0)
    at ../src/lib/eo/eo_base_class.c:2189
#36 0x00007ffff4e11e15 in _ecore_main_loop_iterate_internal (obj=obj@entry=0x40000000036e, pd=pd@entry=0x555555a107c0, once_only=once_only@entry=0)
    at ../src/lib/ecore/ecore_main.c:2466
#37 0x00007ffff4e1265a in _ecore_main_loop_begin (obj=obj@entry=0x40000000036e, pd=pd@entry=0x555555a107c0) at ../src/lib/ecore/ecore_main.c:1231
#38 0x00007ffff4e175b1 in _efl_loop_begin (obj=0x40000000036e, pd=0x555555a107c0) at ../src/lib/ecore/efl_loop.c:57
#39 0x00007ffff4e1674d in efl_loop_begin (obj=0x40000000036e) at src/lib/ecore/efl_loop.eo.c:28
#40 0x00007ffff4e12726 in ecore_main_loop_begin () at ../src/lib/ecore/ecore_main.c:1316
#41 0x00007ffff7737605 in elm_run () at ../src/lib/elementary/elm_main.c:1359
#42 0x000055555555619c in main (argc=<optimized out>, argv=<optimized out>) at ../src/examples/Svg.cpp:180
(gdb) 

```

**Comment by hermet** [comment]
on checking.
