### ISSUE TITLE
Crash on Stress example

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#1120]
When I tested this problem, crash occurred after f887edf562 patch.

bt
```
gdb ./build/src/examples/Stress
....



Thread 1 "Stress" received signal SIGSEGV, Segmentation fault.
cRasterRGBA32 (len=-95350, offset=0, val=0, dst=0x555556b96004) at ../src/lib/sw_engine/tvgSwRasterC.h:27
27	    while (len--) *dst++ = val;
(gdb) bt
#0  cRasterRGBA32 (len=-95350, offset=0, val=0, dst=0x555556b96004) at ../src/lib/sw_engine/tvgSwRasterC.h:27
#1  rasterRGBA32 (len=-5, offset=0, val=0, dst=0x555556b38e40) at ../src/lib/sw_engine/tvgSwRaster.cpp:1435
#2  rasterClear (surface=surface@entry=0x555555db02b0) at ../src/lib/sw_engine/tvgSwRaster.cpp:1551
#3  0x00007ffff7bc09c1 in tvg::SwRenderer::target (this=this@entry=0x555555d96840, region=...) at ../src/lib/sw_engine/tvgSwRenderer.cpp:514
#4  0x00007ffff7bc0bc0 in tvg::SwRenderer::renderShape (data=0x5555568a2f70, this=0x555555d96840) at ../src/lib/sw_engine/tvgSwRenderer.cpp:375
#5  tvg::SwRenderer::renderShape (this=0x555555d96840, data=0x5555568a2f70) at ../src/lib/sw_engine/tvgSwRenderer.cpp:360
#6  0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x7fffd0091620, renderer=...) at ../src/lib/tvgPaint.cpp:181
#7  0x00007ffff7bb8985 in tvg::Scene::Impl::render (this=0x7fffd005e3b0, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#8  0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x7fffd002ddb0, renderer=...) at ../src/lib/tvgPaint.cpp:181
#9  0x00007ffff7bb8985 in tvg::Scene::Impl::render (this=0x7fffd005d890, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#10 0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x7fffd003cd80, renderer=...) at ../src/lib/tvgPaint.cpp:181
#11 0x00007ffff7bb8985 in tvg::Scene::Impl::render (this=0x7fffd00925d0, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#12 0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x7fffd0091770, renderer=...) at ../src/lib/tvgPaint.cpp:181
#13 0x00007ffff7bb8985 in tvg::Scene::Impl::render (this=0x7fffd0092690, renderer=...) at ../src/lib/tvgSceneImpl.h:122
#14 0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x7fffd0092650, renderer=...) at ../src/lib/tvgPaint.cpp:181
#15 0x00007ffff7bb6a3f in tvg::Paint::Impl::render (this=0x5555561bdd30, renderer=...) at ../src/lib/tvgPaint.cpp:181
#16 0x00007ffff7bb533e in tvg::Canvas::Impl::draw (this=0x555555daed60) at ../src/lib/tvgCanvasImpl.h:119
#17 tvg::Canvas::Impl::draw (this=0x555555daed60) at ../src/lib/tvgCanvasImpl.h:113
#18 tvg::Canvas::draw (this=<optimized out>) at ../src/lib/tvgCanvas.cpp:60
#19 0x00005555555566e6 in drawSwView (data=<optimized out>, obj=<optimized out>) at ../src/examples/Stress.cpp:120
#20 0x00007ffff716b22c in evas_process_dirty_pixels (pixels=<optimized out>, surface=<optimized out>, output=<optimized out>, engine=<optimized out>, o=<optimized out>, 
    obj=0x555555dafe40, eo_obj=<optimized out>) at ../src/lib/evas/canvas/evas_object_image.c:1894
#21 _evas_image_pixels_get (eo_obj=eo_obj@entry=0x40000002663e, obj=obj@entry=0x555555dafe40, engine=engine@entry=0x555555cf0600, output=output@entry=0x555555cf30e0, 
    context=context@entry=0x555555a78000, surface=surface@entry=0x5555568fe560, x=<optimized out>, y=<optimized out>, imagew=<optimized out>, imageh=<optimized out>, 
    uvw=<optimized out>, uvh=<optimized out>, filtered=<optimized out>, needs_post_render=0 '\000') at ../src/lib/evas/canvas/evas_object_image.c:2318
#22 0x00007ffff716b7e0 in _evas_image_render (eo_obj=eo_obj@entry=0x40000002663e, obj=obj@entry=0x555555dafe40, engine=engine@entry=0x555555cf0600, 
    output=output@entry=0x555555cf30e0, context=context@entry=0x555555a78000, surface=surface@entry=0x5555568fe560, x=0, y=0, l=0, t=0, r=0, b=0, skip_map=0 '\000', 
    do_async=1 '\001') at ../src/lib/evas/canvas/evas_object_image.c:2468
#23 0x00007ffff716c98e in evas_object_image_render (eo_obj=0x40000002663e, obj=0x555555dafe40, type_private_data=0x555555daff60, engine=0x555555cf0600, output=0x555555cf30e0, 
    context=0x555555a78000, surface=0x5555568fe560, x=0, y=0, do_async=1 '\001') at ../src/lib/evas/canvas/evas_object_image.c:2271
#24 0x00007ffff71d311d in evas_render_mapped (evas=evas@entry=0x555555cdf2c0, eo_obj=eo_obj@entry=0x40000002663e, obj=obj@entry=0x555555dafe40, 
    context=context@entry=0x555555a782f0, output=output@entry=0x555555cf30e0, surface=surface@entry=0x5555568fe560, off_x=<optimized out>, off_y=<optimized out>, 
    mapped=<optimized out>, ecx=<optimized out>, ecy=<optimized out>, ecw=<optimized out>, ech=<optimized out>, proxy_render_data=<optimized out>, level=<optimized out>, 
    do_async=<optimized out>) at ../src/lib/evas/canvas/evas_render.c:2290
#25 0x00007ffff71d4e57 in evas_render_updates_internal_loop (eo_e=eo_e@entry=0x4000000079c3, evas=evas@entry=0x555555cdf2c0, output=0x555555cf30e0, 
    surface=surface@entry=0x5555568fe560, context=context@entry=0x555555a782f0, top=top@entry=0x0, ux=0, uy=0, uw=800, uh=800, cx=0, cy=0, cw=800, ch=800, fx=0, fy=0, 
    skip_cutouts=0 '\000', cutout_margin=0x0, alpha=0 '\000', do_async=1 '\001', offset=0x7fffffffd36c, level=0) at ../src/lib/evas/canvas/evas_render.c:3158
#26 0x00007ffff71d7854 in evas_render_updates_internal (eo_e=eo_e@entry=0x4000000079c3, make_updates=make_updates@entry=1 '\001', do_draw=do_draw@entry=1 '\001', 
    do_async=do_async@entry=1 '\001') at ../src/lib/evas/canvas/evas_render.c:3631
#27 0x00007ffff71d925e in _evas_canvas_render_async (eo_e=0x4000000079c3, e=<optimized out>) at ../src/lib/evas/canvas/evas_render.c:4094
#28 0x00007ffff71542cc in evas_canvas_render_async (obj=<optimized out>) at ../src/lib/evas/canvas/evas_canvas_eo.c:168
#29 0x00007ffff715dc67 in evas_render_async (obj=<optimized out>) at ../src/lib/evas/canvas/evas_canvas_eo.legacy.c:179
#30 0x00007fffe22ba536 in _ecore_evas_x_render (ee=0x555555cdfd00) at ../src/modules/ecore_evas/engines/x/ecore_evas_x.c:761
#31 0x00007ffff4be0de3 in _ecore_evas_idle_enter (data=<optimized out>) at ../src/lib/ecore_evas/ecore_evas.c:295
#32 0x00007ffff6e1a975 in _ecore_call_task_cb (data=<optimized out>, func=<optimized out>) at ../src/lib/ecore/ecore_private.h:456
#33 _ecore_factorized_idle_process (data=0x555555a1d290, event=<optimized out>) at ../src/lib/ecore/ecore_idler.c:35
#34 0x00007ffff4e0c082 in _event_callback_call (legacy_compare=0 '\000', event_info=<optimized out>, desc=0x7ffff707f2d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, pd=0x555555a10760, 
    obj_id=0x4000000001a5) at ../src/lib/eo/eo_base_class.c:2114
#35 _efl_object_event_callback_call (obj_id=0x4000000001a5, pd=0x555555a10760, desc=0x7ffff707f2d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, event_info=<optimized out>)
    at ../src/lib/eo/eo_base_class.c:2186
#36 0x00007ffff4e05d23 in efl_event_callback_call (obj=obj@entry=0x4000000001a5, desc=0x7ffff707f2d0 <_EFL_LOOP_EVENT_IDLE_ENTER>, event_info=event_info@entry=0x0)
    at ../src/lib/eo/eo_base_class.c:2189
#37 0x00007ffff6e1ce15 in _ecore_main_loop_iterate_internal (obj=obj@entry=0x4000000001a5, pd=pd@entry=0x555555a107c0, once_only=once_only@entry=0)
    at ../src/lib/ecore/ecore_main.c:2466
#38 0x00007ffff6e1d65a in _ecore_main_loop_begin (obj=obj@entry=0x4000000001a5, pd=pd@entry=0x555555a107c0) at ../src/lib/ecore/ecore_main.c:1231
#39 0x00007ffff6e225b1 in _efl_loop_begin (obj=0x4000000001a5, pd=0x555555a107c0) at ../src/lib/ecore/efl_loop.c:57
#40 0x00007ffff6e2174d in efl_loop_begin (obj=0x4000000001a5) at src/lib/ecore/efl_loop.eo.c:28
#41 0x00007ffff6e1d726 in ecore_main_loop_begin () at ../src/lib/ecore/ecore_main.c:1316
#42 0x00007ffff7739605 in elm_run () at ../src/lib/elementary/elm_main.c:1359
#43 0x00005555555565ac in main (argc=<optimized out>, argv=<optimized out>) at ../src/examples/Stress.cpp:235
(gdb) 

```

**Comment by hermet** [comment]
@JSUYA Hmm... can't reproduce this issue. is till still valid on the master?
