### ISSUE TITLE
Memory leak when converting invalid SVG file

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1147]
Command:
```
/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png /home/rafal/Desktop/SV/file0.svg -r 1x1
```

```
=================================================================
==59002==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7fb5dca5f9a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7fb5dc7827a1 in _attrParseLinearGradientNode ../src/loaders/svg/tvgSvgLoader.cpp:2401
    #2 0x7fb5dc7a8fb2 in simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) ../src/loaders/svg/tvgXmlParser.cpp:349
    #3 0x7fb5dc78073d in _createLinearGradient ../src/loaders/svg/tvgSvgLoader.cpp:2433
    #4 0x7fb5dc79036a in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2557
    #5 0x7fb5dc790ad8 in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2595
    #6 0x7fb5dc7a95ae in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:417
    #7 0x7fb5dc79200e in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2910
    #8 0x7fb5dc7012e7 in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #9 0x7fb5dc7012e7 in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #10 0x7fb5dc38d693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)

```
[file7.svg.zip](https://github.com/Samsung/thorvg/files/7871609/file7.svg.zip)

**Comment by mgrudzinska** [comment]
please check now (#1150 should solve this)

**Comment by hermet** [comment]
confirmed the fix.
