### ISSUE TITLE
Invalid memory usage when converting svg to png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1211]
```
../src/loaders/svg/tvgSvgLoader.cpp:2877:20: runtime error: null pointer passed as argument 1, which is declared to never be null
AddressSanitizer:DEADLYSIGNAL
=================================================================
==122196==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f9d8ebb33f8 bp 0x7f9d8a0fe930 sp 0x7f9d8a0fe0b0 T1)
==122196==The signal is caused by a READ memory access.
==122196==Hint: address points to the zero page.
    #0 0x7f9d8ebb33f8 in __interceptor_strcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:461
    #1 0x7f9d8e89006e in _gradientDup ../src/loaders/svg/tvgSvgLoader.cpp:2877
    #2 0x7f9d8e8911a8 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2913
    #3 0x7f9d8e890ed8 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2905
    #4 0x7f9d8e890ed8 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2905
    #5 0x7f9d8e894df1 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:3121
    #6 0x7f9d8e7fe36d in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #7 0x7f9d8e7fe36d in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #8 0x7f9d8e477693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)
    #9 0x7f9d8d87d946 in start_thread nptl/pthread_create.c:435
    #10 0x7f9d8d90da43 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x124a43)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:461 in __interceptor_strcmp
Thread T1 created by T0 here:
    #0 0x7f9d8eb79685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7f9d8e477969 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda969)
    #2 0x7f9d8e8058e9 in void __gnu_cxx::new_allocator<std::thread>::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/ext/new_allocator.h:162
    #3 0x7f9d8e8058e9 in void std::allocator_traits<std::allocator<std::thread> >::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::allocator<std::thread>&, std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/alloc_traits.h:512
    #4 0x7f9d8e8058e9 in void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_insert<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:449
    #5 0x7f9d8e7fcad5 in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:121
    #6 0x7f9d8e7fcad5 in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/11/bits/vector.tcc:109
    #7 0x7f9d8e7fcad5 in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int) ../src/lib/tvgTaskScheduler.cpp:113
    #8 0x7f9d8e7fcad5 in tvg::TaskScheduler::init(unsigned int) ../src/lib/tvgTaskScheduler.cpp:170
    #9 0x7f9d8e7c9777 in tvg::Initializer::init(tvg::CanvasEngine, unsigned int) ../src/lib/tvgInitializer.cpp:111
    #10 0x5583c011ab63 in Renderer::createCanvas() ../src/bin/svg2png/svg2png.cpp:144
    #11 0x5583c011b978 in Renderer::render(char const*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ../src/bin/svg2png/svg2png.cpp:64
    #12 0x5583c011daa5 in App::renderFile(char const*) ../src/bin/svg2png/svg2png.cpp:292
    #13 0x5583c011f161 in App::setup(int, char**) ../src/bin/svg2png/svg2png.cpp:233
    #14 0x5583c0117f79 in main ../src/bin/svg2png/svg2png.cpp:343
    #15 0x7f9d8d812fcf in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

==122196==ABORTING

```

[1593.svg.zip](https://github.com/Samsung/thorvg/files/8404122/1593.svg.zip)

**Comment by mgrudzinska** [comment]
solved in #1212
