### ISSUE TITLE
Memory leaks when converting svg to png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1257]
Example files
[AAA.zip](https://github.com/Samsung/thorvg/files/9435682/AAA.zip)

Memory leaks:
[Memory leaks.txt](https://github.com/Samsung/thorvg/files/9435683/Memory.leaks.txt)

Example leak
```
Direct leak of 11 byte(s) in 1 object(s) allocated from:
    #0 0x7f4ea328c9a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7f4ea2f91c06 in _styleCopy ../src/loaders/svg/tvgSvgLoader.cpp:1945
    #2 0x7f4ea2f91c06 in _copyAttr ../src/loaders/svg/tvgSvgLoader.cpp:1993
    #3 0x7f4ea2f91c06 in _cloneNode ../src/loaders/svg/tvgSvgLoader.cpp:2082
    #4 0x7f4ea2f91c06 in _cloneNode ../src/loaders/svg/tvgSvgLoader.cpp:2066
    #5 0x7f4ea2f94ef0 in _attrParseUseNode ../src/loaders/svg/tvgSvgLoader.cpp:2146
    #6 0x7f4ea2fb492d in simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) ../src/loaders/svg/tvgXmlParser.cpp:361
    #7 0x7f4ea2f911ad in _createUseNode ../src/loaders/svg/tvgSvgLoader.cpp:2171
    #8 0x7f4ea2f9735f in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2714
    #9 0x7f4ea2f97c8d in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2792
    #10 0x7f4ea2fb4f29 in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:429
    #11 0x7f4ea2f9994e in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:3112
    #12 0x7f4ea2f00fdd in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #13 0x7f4ea2f00fdd in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #14 0x7f4ea2b5f2c2  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc2c2)

Indirect leak of 576 byte(s) in 3 object(s) allocated from:
    #0 0x7f170deefa37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f170db982fd in _createNode ../src/loaders/svg/tvgSvgLoader.cpp:1177
    #2 0x7f170db98f16 in _createCssStyleNode ../src/loaders/svg/tvgSvgLoader.cpp:1297
    #3 0x7f170dba2486 in _svgLoaderParserXmlCssStyle ../src/loaders/svg/tvgSvgLoader.cpp:2767
    #4 0x7f170dba2486 in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2801
    #5 0x7f170dbbf73f in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:453
    #6 0x7f170dba394e in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:3112
    #7 0x7f170db0afdd in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #8 0x7f170db0afdd in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #9 0x7f170d7692c2  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc2c2)
```

**Comment by mgrudzinska** [comment]
there is still much more to find, I'll comment after all mem leaks are solved

**Comment by mgrudzinska** [comment]
@qarmin could you confirm that everything is ok now? I checked, and there are no mem leaks any more

**Comment by qarmin** [comment]
With valid files from above, I don't have anymore any leaks.
