### ISSUE TITLE
Sanitizer logs

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#461]
```
thirdparty/thorvg/src/lib/sw_engine/tvgSwRle.cpp:97:18: runtime error: left shift of negative value -40
=================================================================
==11415==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6120003ff450 at pc 0x000003f87ad5 bp 0x7fb2683cc790 sp 0x7fb2683cc780
READ of size 1 at 0x6120003ff450 thread T11
    #0 0x3f87ad4 in _simpleXmlSkipXmlEntities thirdparty/thorvg/src/loaders/svg/tvgXmlParser.cpp:145
    #1 0x3f88769 in _skipWhiteSpacesAndXmlEntities thirdparty/thorvg/src/loaders/svg/tvgXmlParser.cpp:182
    #2 0x3f8a711 in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) thirdparty/thorvg/src/loaders/svg/tvgXmlParser.cpp:439
    #3 0x3edef9c in SvgLoader::run(unsigned int) thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:2581
    #4 0x3ea84ad in tvg::Task::operator()(unsigned int) thirdparty/thorvg/src/lib/tvgTaskScheduler.h:68
    #5 0x3eaadfe in tvg::TaskSchedulerImpl::run(unsigned int) thirdparty/thorvg/src/lib/tvgTaskScheduler.cpp:138
    #6 0x3ea9c9f in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const thirdparty/thorvg/src/lib/tvgTaskScheduler.cpp:113
    #7 0x3eb5f11 in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
    #8 0x3eb5dd1 in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_result&&, (tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
    #9 0x3eb5ca7 in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
    #10 0x3eb5be6 in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
    #11 0x3eb5b9c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
    #12 0x17fa69b3 in execute_native_thread_routine (/home/runner/work/godot/godot/bin/godot.linuxbsd.tools.64s+0x17fa69b3)
    #13 0x7fb298784608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
    #14 0x7fb297be9292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)````

**Comment by hermet** [comment]
@fire hopefull this is fixed by https://github.com/Samsung/thorvg/pull/467

**Comment by fire** [comment]
Verifying now. 

1. Need to update the Godot Engine pull request to the latest master of both godot engine and thorvg
2. Make the builds
3. Verify svgs

**Comment by fire** [comment]
This is resolved because the CICD isn't complaining anymore.

Thanks.
