### ISSUE TITLE
Freeze(due to using threads?) when tying to convert image

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#488]
[a-stroke-dasharray-005.svg.zip](https://github.com/Samsung/thorvg/files/6699246/a-stroke-dasharray-005.svg.zip)

```
Thread 1 "svg2png" received signal SIGINT, Interrupt.
futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x6120000006c0) at ../sysdeps/nptl/futex-internal.h:183
183	../sysdeps/nptl/futex-internal.h: Nie ma takiego pliku ani katalogu.
(gdb) backtrace
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x6120000006c0) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x612000000670, cond=0x612000000698) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x612000000698, mutex=0x612000000670) at pthread_cond_wait.c:638
#3  0x00007ffff7010e50 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff73294b7 in tvg::Task::done (this=this@entry=0x612000000668) at ../src/lib/tvgTaskScheduler.h:58
#5  0x00007ffff7357330 in SvgLoader::scene (this=0x612000000640) at ../src/loaders/svg/tvgSvgLoader.cpp:2733
#6  0x00007ffff72d966a in tvg::Picture::Impl::reload (this=this@entry=0x6060000002c0) at /usr/include/c++/9/bits/shared_ptr_base.h:1309
#7  0x00007ffff72daf73 in tvg::Picture::Impl::update (pFlag=tvg::All, clips=..., opacity=255, transform=0x0, renderer=..., this=0x6060000002c0) at ../src/lib/tvgPictureImpl.h:119
#8  tvg::PaintMethod<tvg::Picture::Impl>::update (this=0x602000000070, renderer=..., transform=0x0, opacity=255, clips=..., flag=tvg::All) at ../src/lib/tvgPaint.h:145
#9  0x00007ffff72cfc82 in tvg::Paint::Impl::update (this=this@entry=0x604000000050, renderer=..., pTransform=pTransform@entry=0x0, opacity=opacity@entry=255, clips=..., pFlag=pFlag@entry=127)
    at ../src/lib/tvgPaint.cpp:231
#10 0x00007ffff72c5138 in tvg::Canvas::Impl::update (this=this@entry=0x603000000190, paint=paint@entry=0x6030000001c0, force=force@entry=true) at ../src/lib/tvgCanvasImpl.h:96
#11 0x00007ffff72c3a0e in tvg::Canvas::Impl::push (paint=std::unique_ptr<class tvg::Paint> = {...}, this=0x603000000190) at ../src/lib/tvgCanvasImpl.h:57
#12 tvg::Canvas::push (this=<optimized out>, paint=...) at ../src/lib/tvgCanvas.cpp:48
#13 0x00005555555eadaf in App::tvgDrawCmds (this=<optimized out>, canvas=0x603000000160, useSvgSize=<optimized out>) at /usr/include/c++/9/bits/move.h:74
#14 0x00005555555eb4a7 in App::tvgRender (this=0x7fffffffdab0, w=200, h=200) at /usr/include/c++/9/bits/unique_ptr.h:360
#15 0x00005555555e6e67 in main (argc=<optimized out>, argv=<optimized out>) at ../src/bin/svg2png/svg2png.cpp:231

```

**Comment by hermet** [comment]
fall in infinite loop while parsing svg  => stroke-dasharray="1em,0.5em,2em"
stroke doesn't expect "em" unit.

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/529
