### ISSUE TITLE
Memory leak when converting image

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#492]
[com.github.qarmin.czkawka.svg.zip](https://github.com/Samsung/thorvg/files/6699310/com.github.qarmin.czkawka.svg.zip)

```
Direct leak of 96 byte(s) in 3 object(s) allocated from:
    #0 0x7f1e54559947 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x7f1e5422b805 in _idFromUrl ../src/loaders/svg/tvgSvgLoader.cpp:282
    #2 0x7f1e5422ee7e in _handleClipPathAttr ../src/loaders/svg/tvgSvgLoader.cpp:870
    #3 0x7f1e54235efe in _attrParseGNode ../src/loaders/svg/tvgSvgLoader.cpp:963
    #4 0x7f1e54257eb3 in simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) ../src/loaders/svg/tvgXmlParser.cpp:319
    #5 0x7f1e5423e27c in _createGNode ../src/loaders/svg/tvgSvgLoader.cpp:1073
    #6 0x7f1e54243563 in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2189
    #7 0x7f1e54244213 in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2247
    #8 0x7f1e542580dc in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:425
    #9 0x7f1e542455c5 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2605
    #10 0x7f1e541d5c5d in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #11 0x7f1e541d5c5d in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #12 0x7f1e541d69e3 in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/lib/tvgTaskScheduler.cpp:113
    #13 0x7f1e541d69e3 in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
    #14 0x7f1e541d69e3 in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_result&&, (tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
    #15 0x7f1e541d69e3 in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
    #16 0x7f1e541d69e3 in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
    #17 0x7f1e541d69e3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
    #18 0x7f1e53ef6d83  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6d83)

```

**Comment by hermet** [comment]
fixed by https://github.com/Samsung/thorvg/pull/505
