### ISSUE TITLE
Trying to write data to wild pointer when converting image

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#493]
[com.github.qarmin.czkawka.Devel.svg.zip](https://github.com/Samsung/thorvg/files/6699314/com.github.qarmin.czkawka.Devel.svg.zip)

```
==19494==ERROR: AddressSanitizer: SEGV on unknown address 0x60306dfffff2 (pc 0x7f02c3703b2f bp 0x000000000000 sp 0x7ffc1f2febe0 T0)
==19494==The signal is caused by a WRITE memory access.
    #0 0x7f02c3703b2e  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x28b2e)
    #1 0x7f02c37eb8a8 in operator delete(void*) (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x1108a8)
    #2 0x7f02c34bbc00 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() /usr/include/c++/9/bits/basic_string.h:658
    #3 0x7f02c34bbc00 in _freeNodeStyle ../src/loaders/svg/tvgSvgLoader.cpp:2465
    #4 0x7f02c34bbc00 in _freeNode ../src/loaders/svg/tvgSvgLoader.cpp:2484
    #5 0x7f02c34bb6e5 in _freeNode ../src/loaders/svg/tvgSvgLoader.cpp:2478
    #6 0x7f02c34bb6e5 in _freeNode ../src/loaders/svg/tvgSvgLoader.cpp:2478
    #7 0x7f02c34bc1ec in _freeNode ../src/loaders/svg/tvgSvgLoader.cpp:2499
    #8 0x7f02c34ca347 in SvgLoader::close() ../src/loaders/svg/tvgSvgLoader.cpp:2721
    #9 0x7f02c344a85e in tvg::Picture::Impl::reload() ../src/lib/tvgPictureImpl.h:103
    #10 0x7f02c344bf72 in tvg::Picture::Impl::update(tvg::RenderMethod&, tvg::RenderTransform const*, unsigned int, tvg::Array<void*>&, tvg::RenderUpdateFlag) ../src/lib/tvgPictureImpl.h:119
    #11 0x7f02c344bf72 in tvg::PaintMethod<tvg::Picture::Impl>::update(tvg::RenderMethod&, tvg::RenderTransform const*, unsigned int, tvg::Array<void*>&, tvg::RenderUpdateFlag) ../src/lib/tvgPaint.h:145
    #12 0x7f02c3440c81 in tvg::Paint::Impl::update(tvg::RenderMethod&, tvg::RenderTransform const*, unsigned int, tvg::Array<void*>&, unsigned int) ../src/lib/tvgPaint.cpp:231
    #13 0x7f02c3436137 in tvg::Canvas::Impl::update(tvg::Paint*, bool) (/home/rafal/thorvg/build/src/bin/svg2png/../../libthorvg.so.0+0x1a4137)
    #14 0x7f02c3434a0d in tvg::Canvas::Impl::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) ../src/lib/tvgCanvasImpl.h:57
    #15 0x7f02c3434a0d in tvg::Canvas::push(std::unique_ptr<tvg::Paint, std::default_delete<tvg::Paint> >) ../src/lib/tvgCanvas.cpp:48
    #16 0x55719ed57dae in App::tvgDrawCmds(tvg::Canvas*, bool) ../src/bin/svg2png/svg2png.cpp:93
    #17 0x55719ed584a6 in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:124
    #18 0x55719ed53e66 in main ../src/bin/svg2png/svg2png.cpp:231
    #19 0x7f02c255e0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #20 0x55719ed53f8d in _start (/home/rafal/thorvg/build/src/bin/svg2png/svg2png+0x92f8d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x28b2e) 
```

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/505/commits
