### ISSUE TITLE
Invalid read in _appendShape when converting svg file in svg2png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#495]
[e-polygon-002.svg.zip](https://github.com/Samsung/thorvg/files/6699347/e-polygon-002.svg.zip)
```
==26952==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000103c at pc 0x7f94620fe6a9 bp 0x7f945d9fe420 sp 0x7f945d9fe410
READ of size 4 at 0x60200000103c thread T1
    #0 0x7f94620fe6a8 in _appendShape ../src/loaders/svg/tvgSvgSceneBuilder.cpp:295
    #1 0x7f946210215a in _shapeBuildHelper ../src/loaders/svg/tvgSvgSceneBuilder.cpp:268
    #2 0x7f946210215a in _sceneBuildHelper ../src/loaders/svg/tvgSvgSceneBuilder.cpp:343
    #3 0x7f9462102b98 in svgSceneBuild(SvgNode*, float, float, float, float) ../src/loaders/svg/tvgSvgSceneBuilder.cpp:364
    #4 0x7f94620f3f81 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2617
    #5 0x7f9462083c5d in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #6 0x7f9462083c5d in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #7 0x7f94620849e3 in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/lib/tvgTaskScheduler.cpp:113
    #8 0x7f94620849e3 in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
    #9 0x7f94620849e3 in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_result&&, (tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
    #10 0x7f94620849e3 in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
    #11 0x7f94620849e3 in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
    #12 0x7f94620849e3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
    #13 0x7f9461da4d83  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6d83)
    #14 0x7f9461127608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
    #15 0x7f9461276292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

0x60200000103c is located 0 bytes to the right of 12-byte region [0x602000001030,0x60200000103c)
allocated by thread T1 here:
    #0 0x7f9462405ffe in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dffe)
    #1 0x7f94620dd4a5 in _attrParsePolygonPoints ../src/loaders/svg/tvgSvgLoader.cpp:1295
    #2 0x7f94620dd4a5 in _attrParsePolygonNode ../src/loaders/svg/tvgSvgLoader.cpp:1324
    #3 0x7f9462105eb3 in simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) ../src/loaders/svg/tvgXmlParser.cpp:319
    #4 0x7f94620ecb11 in _createPolygonNode ../src/loaders/svg/tvgSvgLoader.cpp:1346
    #5 0x7f94620f1a67 in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2202
    #6 0x7f94620f2213 in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2247
    #7 0x7f94621060dc in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:425
    #8 0x7f94620f35c5 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2605
    #9 0x7f9462083c5d in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #10 0x7f9462083c5d in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #11 0x7f94620849e3 in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}::operator()() const ../src/lib/tvgTaskScheduler.cpp:113
    #12 0x7f94620849e3 in void std::__invoke_impl<void, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_other, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/invoke.h:60
    #13 0x7f94620849e3 in std::__invoke_result<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>::type std::__invoke<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::__invoke_result&&, (tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&)...) /usr/include/c++/9/bits/invoke.h:95
    #14 0x7f94620849e3 in void std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/include/c++/9/thread:244
    #15 0x7f94620849e3 in std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> >::operator()() /usr/include/c++/9/thread:251
    #16 0x7f94620849e3 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}> > >::_M_run() /usr/include/c++/9/thread:195
    #17 0x7f9461da4d83  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd6d83)

Thread T1 created by T0 here:
    #0 0x7f9462332805 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x7f9461da5048 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xd7048)
    #2 0x7f9462088c17 in void __gnu_cxx::new_allocator<std::thread>::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/ext/new_allocator.h:147
    #3 0x7f9462088c17 in void std::allocator_traits<std::allocator<std::thread> >::construct<std::thread, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(std::allocator<std::thread>&, std::thread*, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/alloc_traits.h:484
    #4 0x7f9462088c17 in void std::vector<std::thread, std::allocator<std::thread> >::_M_realloc_insert<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(__gnu_cxx::__normal_iterator<std::thread*, std::vector<std::thread, std::allocator<std::thread> > >, tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/vector.tcc:449
    #5 0x7f946208210e in void std::vector<std::thread, std::allocator<std::thread> >::emplace_back<tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}>(tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int)::{lambda()#1}&&) /usr/include/c++/9/bits/vector.tcc:121
    #6 0x7f946208210e in tvg::TaskSchedulerImpl::TaskSchedulerImpl(unsigned int) ../src/lib/tvgTaskScheduler.cpp:113
    #7 0x7f946208210e in tvg::TaskScheduler::init(unsigned int) ../src/lib/tvgTaskScheduler.cpp:170
    #8 0x7f94620558e6 in tvg::Initializer::init(tvg::CanvasEngine, unsigned int) ../src/lib/tvgInitializer.cpp:70
    #9 0x555d5eba5243 in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:104
    #10 0x555d5eba0e66 in main ../src/bin/svg2png/svg2png.cpp:231
    #11 0x7f946117b0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../src/loaders/svg/tvgSvgSceneBuilder.cpp:295 in _appendShape

```

**Comment by hermet** [comment]
still valid...

**Comment by hermet** [comment]
@qarmin  fixed by https://github.com/Samsung/thorvg/pull/504
