### ISSUE TITLE
Invalid write in fillFetchLinear when converting svg file in svg2png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#496]
[exchange-positions.svg.zip](https://github.com/Samsung/thorvg/files/6699370/exchange-positions.svg.zip)

```
==29655==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0000000d0 at pc 0x7f635a026cf5 bp 0x7ffe82b2cf00 sp 0x7ffe82b2cef0
WRITE of size 4 at 0x60d0000000d0 thread T0
    #0 0x7f635a026cf4 in fillFetchLinear(SwFill const*, unsigned int*, unsigned int, unsigned int, unsigned int) ../src/lib/sw_engine/tvgSwFill.cpp:252
    #1 0x7f635a038213 in _rasterOpaqueLinearGradientRect ../src/lib/sw_engine/tvgSwRaster.cpp:701
    #2 0x7f635a038213 in rasterGradientShape(SwSurface*, SwShape*, unsigned int) ../src/lib/sw_engine/tvgSwRaster.cpp:1109
    #3 0x7f635a046376 in tvg::SwRenderer::renderShape(void*) ../src/lib/sw_engine/tvgSwRenderer.cpp:360
    #4 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #5 0x7f635a009d60 in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #6 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #7 0x7f635a009d60 in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #8 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #9 0x7f635a009d60 in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #10 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #11 0x7f635a009d60 in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #12 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #13 0x7f6359ff4470 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #14 0x7f6359fec9f1 in tvg::Canvas::Impl::draw() (/home/rafal/thorvg/build/src/bin/svg2png/../../libthorvg.so.0+0x1a49f1)
    #15 0x7f6359feacfb in tvg::Canvas::draw() ../src/lib/tvgCanvas.cpp:60
    #16 0x5561bfee681a in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:133
    #17 0x5561bfee1e66 in main ../src/bin/svg2png/svg2png.cpp:231
    #18 0x7f63591140b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #19 0x5561bfee1f8d in _start (/home/rafal/thorvg/build/src/bin/svg2png/svg2png+0x92f8d)

0x60d0000000d0 is located 0 bytes to the right of 144-byte region [0x60d000000040,0x60d0000000d0)
allocated by thread T0 here:
    #0 0x7f635a39effe in __interceptor_realloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x10dffe)
    #1 0x5561bfee65b1 in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:128
    #2 0x5561bfee1e66 in main ../src/bin/svg2png/svg2png.cpp:231
    #3 0x7f63591140b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../src/lib/sw_engine/tvgSwFill.cpp:252 in fillFetchLinear(SwFill const*, unsigned int*, unsigned int, unsigned int, unsigned int)
```

**Comment by hermet** [comment]
@qarmin i think svg2png app has a wrong implementation, this patch may fix all other issues you reported. i will check it tmr =>  https://github.com/Samsung/thorvg/pull/500
