### ISSUE TITLE
Memory leak when converting ArchiveManager svg (svg2png)

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#547]
[org.gnome.ArchiveManager.Devel.svg.zip](https://github.com/Samsung/thorvg/files/6743404/org.gnome.ArchiveManager.Devel.svg.zip)

```
../src/lib/tvgArray.h:78:15: runtime error: null pointer passed as argument 1, which is declared to never be null
../src/lib/tvgArray.h:78:15: runtime error: null pointer passed as argument 2, which is declared to never be null

=================================================================
==83655==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fd9754375a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7fd975136afa in tvg::SwRenderer::target(tvg::RenderRegion const&) ../src/lib/sw_engine/tvgSwRenderer.cpp:449
    #2 0x7fd9750e853e in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:172
    #3 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #4 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #5 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #6 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #7 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #8 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #9 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #10 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #11 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #12 0x7fd9750e17e7 in tvg::Canvas::Impl::draw() ../src/lib/tvgCanvasImpl.h:118
    #13 0x7fd9750dfae5 in tvg::Canvas::draw() ../src/lib/tvgCanvas.cpp:60
    #14 0x556ff1609469 in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:106
    #15 0x556ff1604f03 in main ../src/bin/svg2png/svg2png.cpp:201
    #16 0x7fd9741d7564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)

Indirect leak of 65536 byte(s) in 1 object(s) allocated from:
    #0 0x7fd975435c47 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7fd97513709a in tvg::SwRenderer::target(tvg::RenderRegion const&) ../src/lib/sw_engine/tvgSwRenderer.cpp:459
    #2 0x7fd9750e853e in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:172
    #3 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #4 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #5 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #6 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #7 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #8 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #9 0x7fd9750fe73e in tvg::Scene::Impl::render(tvg::RenderMethod&) ../src/lib/tvgSceneImpl.h:96
    #10 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #11 0x7fd9750e8c27 in tvg::Paint::Impl::render(tvg::RenderMethod&) ../src/lib/tvgPaint.cpp:179
    #12 0x7fd9750e17e7 in tvg::Canvas::Impl::draw() ../src/lib/tvgCanvasImpl.h:118
    #13 0x7fd9750dfae5 in tvg::Canvas::draw() ../src/lib/tvgCanvas.cpp:60
    #14 0x556ff1609469 in App::tvgRender(int, int) ../src/bin/svg2png/svg2png.cpp:106
    #15 0x556ff1604f03 in main ../src/bin/svg2png/svg2png.cpp:201
    #16 0x7fd9741d7564 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28564)
```

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/585
