### ISSUE TITLE
Memory leak related to gradients (svg2png)

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#548]
[TFL_TFW_2nd_window_Launch.svg.zip](https://github.com/Samsung/thorvg/files/6743414/TFL_TFW_2nd_window_Launch.svg.zip)

```
../src/lib/tvgArray.h:78:15: runtime error: null pointer passed as argument 1, which is declared to never be null
../src/lib/tvgArray.h:78:15: runtime error: null pointer passed as argument 2, which is declared to never be null

=================================================================
==92837==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 320 byte(s) in 4 object(s) allocated from:
    #0 0x7f5caab80e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f5caa8c87cd in _cloneGradient ../src/loaders/svg/tvgSvgLoader.cpp:1565
    #2 0x7f5caa8c87cd in _gradientDup ../src/loaders/svg/tvgSvgLoader.cpp:2394
    #3 0x7f5caa8c97e0 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2427
    #4 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #5 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #6 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #7 0x7f5caa8cc06d in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2620
    #8 0x7f5caa85bf3e in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #9 0x7f5caa85bf3e in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #10 0x7f5caa54d693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7f5caab80e17 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7f5caa8c87cd in _cloneGradient ../src/loaders/svg/tvgSvgLoader.cpp:1565
    #2 0x7f5caa8c87cd in _gradientDup ../src/loaders/svg/tvgSvgLoader.cpp:2394
    #3 0x7f5caa8c97e0 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2427
    #4 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #5 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #6 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #7 0x7f5caa8c96b1 in _updateGradient ../src/loaders/svg/tvgSvgLoader.cpp:2423
    #8 0x7f5caa8cc06d in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2620
    #9 0x7f5caa85bf3e in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #10 0x7f5caa85bf3e in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #11 0x7f5caa54d693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)
```

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/584/commits/da874293490356efdfdc538f81150162ba4b414e
