### ISSUE TITLE
Multiple id cause memory leak when converting svg 

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#593]
svg file
```
<svg width="100" height="100">
<g id="" id="">
</g>
</svg>
```

```
Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f3baab065a7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x7f3baa81b0aa in _copyId ../src/loaders/svg/tvgSvgLoader.cpp:55
    #2 0x7f3baa827f58 in _attrParseGNode ../src/loaders/svg/tvgSvgLoader.cpp:993
    #3 0x7f3baa851cf4 in simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) ../src/loaders/svg/tvgXmlParser.cpp:319
    #4 0x7f3baa832f0d in _createGNode ../src/loaders/svg/tvgSvgLoader.cpp:1108
    #5 0x7f3baa83a440 in _svgLoaderParserXmlOpen ../src/loaders/svg/tvgSvgLoader.cpp:2348
    #6 0x7f3baa83b20b in _svgLoaderParser ../src/loaders/svg/tvgSvgLoader.cpp:2408
    #7 0x7f3baa851f17 in simpleXmlParse(char const*, unsigned int, bool, bool (*)(void*, SimpleXMLType, char const*, unsigned int), void const*) ../src/loaders/svg/tvgXmlParser.cpp:425
    #8 0x7f3baa83c5f9 in SvgLoader::run(unsigned int) ../src/loaders/svg/tvgSvgLoader.cpp:2757
    #9 0x7f3baa7c9608 in tvg::Task::operator()(unsigned int) ../src/lib/tvgTaskScheduler.h:68
    #10 0x7f3baa7c9608 in tvg::TaskSchedulerImpl::run(unsigned int) ../src/lib/tvgTaskScheduler.cpp:138
    #11 0x7f3baa4ad693  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xda693)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
```

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/597
